MVC/BEST_HOOKAH/BestHookah.Web/BestHookah.AdminEx/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BestHookah.DAL;

namespace BestHookah.AdminEx.Controllers
{
    public class AboutUsController : Controller
    {
        BestHookahEntities db = new BestHookahEntities();
        // GET: AboutUs
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Menu()
        {
            return View();
        }

        public ActionResult Events()
        {
            return View();
        }

        //NormalView
        public ActionResult Contacts()
        {
            return View(db.Branches.ToList());
        }

        #region Branches
        public ActionResult BranchList()
        {
            List<Branches> branches = db.Branches.ToList();
            return View(branches);
        }

        public ActionResult CreateBranch()
        {
            Branches branches = new Branches();
            return View(branches);
        }
        [HttpPost]
        public ActionResult CreateBranchPost(Branches branches)
        {
            string message = "";

            if (BLL.Service.CreateBranch(branches, out message))
                return RedirectToAction("BranchList");
            else
                return RedirectToAction("CreateBranch", new { branches = branches, message = message });
        }


        public ActionResult EditBranch(int id)
        {
            Branches branches = db.Branches.ToList().First(p => p.Id == id);
            return View(branches);
        }
        [HttpPost]
        public ActionResult EditBranchPost(Branches branches)
        {
            string message = "";

            if (BLL.Service.EditBranch(branches, out message))
                return RedirectToAction("BranchList");
            else
                return RedirectToAction($"EditBranch/{branches.Id}", new { branches = branches, message = message });
        }


        public ActionResult DeleteBranch(int id)
        {
            Branches branches = db.Branches.ToList().First(p => p.Id == id);
            return View(branches);
        }
        [HttpPost]
        public ActionResult DeleteBranchPost(Branches branches)
        {
            string message = "";

            if (BLL.Service.DeleteBranch(branches, out message))
                return RedirectToAction("BranchList");
            else
                return RedirectToAction($"DeleteBranch/{branches.Id}", new { branches = branches, message = message });
        }

        #endregion

        #region Blog/Events
        //Normal View
        public ActionResult Blog()
        {
            List<EventsOnSite> events = db.EventsOnSite.ToList();
            if (RouteData.Values["id"] == null)
            {
                ViewBag.RouteId = 1;
                return View(events);
            }
            else
            {
                int id = Int32.Parse(RouteData.Values["id"].ToString());
                ViewBag.RouteId = id;
                return View(events);
            }
        }

        public ActionResult BlogButtonReadMore(int id)
        {
            List<EventsOnSite> events = db.EventsOnSite.ToList();
            ViewBag.EventsOnSite = events;
            if (events.ElementAtOrDefault(id - 1) != null)
            {
                return View(events.ElementAt(id - 1));
            }
            else
            {
                return RedirectToAction("Blog");
            }
        }

        //Create Blog
        public ActionResult CreateEventOnSite()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateEventOnSitePost(EventsOnSite eventsOnSite)
        {
            string message = "";

            if (BLL.Service.CreateEventOnSite(eventsOnSite, out message))
                return RedirectToAction("Blog");
            else
                return RedirectToAction("CreateEventOnSite", new { hookahBarDrinks = eventsOnSite, message = message });
        }
        #endregion

        #region HookahBar
        //Normal View
        public ActionResult HookahBarDrinks()
        {
            List<HookahBarDrinks> bar = db.HookahBarDrinks.ToList();
            ViewData["MenuSections"] = db.MenuSections.ToList();
            return View(bar);
        }

        //MenuItems View
        public ActionResult HookahBarDrinksList()
        {
            List<HookahBarDrinks> bar = db.HookahBarDrinks.ToList();
            return View(bar);
        }

        //MenuSections View
        public ActionResult HookahBarDrinksMenuSections()
        {
            List<MenuSections> bar = db.MenuSections.ToList();
            return View(bar);
        }

        #region Create/Delete/Edit MenuItems
        ////////////////////////////////////
        public ActionResult CreateHookahBarDrinks()
        {
            HookahBarDrinks HookahBarDrinks = new HookahBarDrinks();
            return View(HookahBarDrinks);
        }

        [HttpPost]
        public ActionResult CreateMenuItem(HookahBarDrinks hookahBarDrinks)
        {
            string message = "";

            if (BLL.Service.CreateHookahBarDrinks(hookahBarDrinks, out message))
                return RedirectToAction("HookahBarDrinksList");
            else
                return RedirectToAction("CreateMenuItem", new { hookahBarDrinks = hookahBarDrinks, message = message });
        }

        ////////////////////////////////////
        public ActionResult EditHookahBarDrinks(int id)
        {
            HookahBarDrinks HookahBarDrinks = db.HookahBarDrinks.ToList().FirstOrDefault(p => p.Id == id);
            return View(HookahBarDrinks);
        }

        [HttpPost]
        public ActionResult EditMenuItem(HookahBarDrinks hookahBarDrinks)
        {
            string message = "";

            if (BLL.Service.EditHookahBarDrinks(hookahBarDrinks, out message))
                return RedirectToAction("HookahBarDrinksList");
            else
                return RedirectToAction($"EditMenuItem/{hookahBarDrinks.Id}", new { hookahBarDrinks = hookahBarDrinks, message = message });
        }

        ////////////////////////////////////
        public ActionResult DeleteHookahBarDrinks(int id)
        {
            HookahBarDrinks HookahBarDrinks = db.HookahBarDrinks.ToList().FirstOrDefault(p => p.Id == id);
            return View(HookahBarDrinks);
        }

        [HttpPost]
        public ActionResult DeleteMenuItem(HookahBarDrinks hookahBarDrinks)
        {
            string message = "";

            if (BLL.Service.DeleteHookahBarDrinks(hookahBarDrinks, out message))
                return RedirectToAction("HookahBarDrinksList");
            else
                return RedirectToAction($"DeleteMenuItem/{hookahBarDrinks.Id}", new { hookahBarDrinks = hookahBarDrinks, message = message });
        }

        public ActionResult DescriptionMenuItem(int id)
        {
            HookahBarDrinks HookahBarDrinks = db.HookahBarDrinks.ToList().FirstOrDefault(p => p.Id == id);
            return View(HookahBarDrinks);
        }
        #endregion

        #region Create/Delete/Edit MenuSections

        public ActionResult CreateMenuSection()
        {
            MenuSections menuSections = new MenuSections();
            return View(menuSections);
        }
        [HttpPost]
        public ActionResult CreateMenuSectionPost(MenuSections menuSections)
        {
            string message = "";

            if (BLL.Service.CreateMenuSection(menuSections, out message))
                return RedirectToAction("HookahBarDrinksMenuSections");
            else
                return RedirectToAction("CreateMenuSectionsPost", new { menuSections = menuSections, message = message });
        }

        ////////////////////////////////////
        public ActionResult EditMenuSection(int id)
        {
            MenuSections MenuSections = db.MenuSections.ToList().FirstOrDefault(p => p.Id == id);
            return View(MenuSections);
        }
        [HttpPost]
        public ActionResult EditMenuSectionPost(MenuSections menuSections)
        {
            string message = "";

            if (BLL.Service.EditMenuSection(menuSections, out message))
                return RedirectToAction("HookahBarDrinksMenuSections");
            else
                return RedirectToAction($"EditMenuSectionsPost/{menuSections.Id}", new { menuSections = menuSections, message = message });
        }

        ////////////////////////////////////
        public ActionResult DeleteMenuSection(int id)
        {
            MenuSections MenuSections = db.MenuSections.ToList().FirstOrDefault(p => p.Id == id);
            return View(MenuSections);
        }
        [HttpPost]
        public ActionResult DeleteMenuSectionPost(MenuSections menuSections)
        {
            string message = "";

            if (BLL.Service.DeleteMenuSection(menuSections, out message))
                return RedirectToAction("HookahBarDrinksMenuSections");
            else
                return RedirectToAction($"DeleteMenuSectionsPost/{menuSections.Id}", new { menuSections = menuSections, message = message });
        }

        ////////////////////////////////////
        public ActionResult DescriptionMenuSection(int id)
        {
            MenuSections MenuSections = db.MenuSections.ToList().FirstOrDefault(p => p.Id == id);
            return View(MenuSections);
        }

        #endregion

        #endregion
    }
}

MVC/BEST_HOOKAH/BestHookah.Web/BestHookah.AdminEx/Views/AboutUs/BranchList.cshtml
@model IEnumerable<BestHookah.DAL.Branches>

@{
    ViewBag.Title = "BranchList";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}

<h2>BranchList</h2>

<p>
    @Html.ActionLink("Create New", "CreateBranch")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BranchName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoursOfOperations)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BranchName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HoursOfOperations)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditBranch", new { id=item.Id }) |
            @Html.ActionLink("Delete", "DeleteBranch", new { id=item.Id })
        </td>
    </tr>
}

</table>

MVC/BEST_HOOKAH/BestHookah.Web/BestHookah.AdminEx/Views/AboutUs/CreateBranch.cshtml
@model BestHookah.DAL.Branches

@{
    ViewBag.Title = "CreateBranch";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}

<h2>CreateBranch</h2>


@using (Html.BeginForm("CreateBranchPost","AboutUs", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Branches</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BranchName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BranchName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BranchName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoursOfOperations, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoursOfOperations, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoursOfOperations, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "BranchList")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/BEST_HOOKAH/BestHookah.Web/BestHookah.AdminEx/Views/AboutUs/CreateMenuSection.cshtml
@model BestHookah.DAL.MenuSections

@{
    ViewBag.Title = "CreateMenuSection";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}

<h2>CreateMenuSection</h2>


@using (Html.BeginForm("CreateMenuSectionPost", "AboutUs", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MenuSections</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "HookahBarDrinksMenuSections")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/BEST_HOOKAH/BestHookah.Web/BestHookah.AdminEx/Views/AboutUs/DeleteBranch.cshtml
@model BestHookah.DAL.Branches

@{
    ViewBag.Title = "DeleteBranch";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}

<h2>DeleteBranch</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Branches</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BranchName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BranchName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoursOfOperations)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoursOfOperations)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteBranchPost", "AboutUs", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.BranchName)
        @Html.HiddenFor(model => model.Description)
        @Html.HiddenFor(model => model.Address)
        @Html.HiddenFor(model => model.Phone)
        @Html.HiddenFor(model => model.HoursOfOperations)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "BranchList")
        </div>
    }
</div>

MVC/BEST_HOOKAH/BestHookah.Web/BestHookah.AdminEx/Views/AboutUs/DeleteMenuSection.cshtml
@model BestHookah.DAL.MenuSections

@{
    ViewBag.Title = "DeleteMenuSection";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}

<h2>DeleteMenuSection</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MenuSections</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteMenuSectionPost", "AboutUs", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(Model => Model.Id)
        @Html.HiddenFor(Model => Model.Name)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "HookahBarDrinksMenuSections")
        </div>
    }
</div>

MVC/BEST_HOOKAH/BestHookah.Web/BestHookah.AdminEx/Views/AboutUs/DescriptionHookahBarDrinks.cshtml
@model BestHookah.DAL.HookahBarDrinks

@{
    ViewBag.Title = "DescriptionHookahBarDrinks";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}

<h2>DescriptionHookahBarDrinks</h2>

<div>
    <h4>HookahBarDrinks</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImgPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImgPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TableName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TableName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditHookahBarDrinks", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "HookahBarDrinksList")
</p>

MVC/BEST_HOOKAH/BestHookah.Web/BestHookah.AdminEx/Views/AboutUs/DescriptionMenuSection.cshtml
@model BestHookah.DAL.MenuSections

@{
    ViewBag.Title = "DescriptionMenuSection";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}

<h2>DescriptionMenuSection</h2>

<div>
    <h4>MenuSections</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditMenuSection", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "HookahBarDrinksMenuSections")
</p>

MVC/BEST_HOOKAH/BestHookah.Web/BestHookah.AdminEx/Views/AboutUs/EditBranch.cshtml
@model BestHookah.DAL.Branches

@{
    ViewBag.Title = "EditBranch";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}

<h2>EditBranch</h2>


@using (Html.BeginForm("EditBranchPost","AboutUs",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Branches</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.BranchName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BranchName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BranchName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoursOfOperations, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoursOfOperations, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoursOfOperations, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "BranchList")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/BEST_HOOKAH/BestHookah.Web/BestHookah.AdminEx/Views/AboutUs/EditHookahBarDrinks.cshtml
@model BestHookah.DAL.HookahBarDrinks

@{
    ViewBag.Title = "EditHookahBarDrinks";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}

<h2>EditHookahBarDrinks</h2>


@using (Html.BeginForm("EditMenuItem", "AboutUs", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HookahBarDrinks</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } }.ToString().Replace(",", "."))
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImgPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImgPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImgPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TableName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TableName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TableName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "HookahBarDrinksList")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/BEST_HOOKAH/BestHookah.Web/BestHookah.AdminEx/Views/AboutUs/EditMenuSection.cshtml
@model BestHookah.DAL.MenuSections

@{
    ViewBag.Title = "EditMenuSection";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}

<h2>EditMenuSection</h2>


@using (Html.BeginForm("EditMenuSectionPost", "AboutUs", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MenuSections</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "HookahBarDrinksMenuSections")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}